-- 코드를 입력하세요
SELECT DISTINCT CRCC.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR CRCC INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY CRCRH
ON CRCC.CAR_ID = CRCRH.CAR_ID
WHERE CRCC.CAR_TYPE = '세단' AND TO_CHAR(START_DATE, 'YYYY-MM') = '2022-10'
ORDER BY CRCC.CAR_ID DESC